DGC2/Controllers/CustomerSubController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGC2.Controllers
{
    public class CustomerSubController : Controller
    {

        // GET: CustomerSub
         CustomerSubManager csm = new CustomerSubManager(new EfCustomerAddSubDal());
        AppointmentManager apm = new AppointmentManager(new EfAppointmentDal());
        public ActionResult Index()
        {
            var customersubvalues = csm.GetList();
            return View(customersubvalues);
        }
        [HttpGet]
        public ActionResult AddSubCustomer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddSubCustomer(SubCustomer p)
        {
            csm.SubCustomerAdd(p);
            return RedirectToAction("/CustomerAppAccept/SubCustomerList");
        }
        [HttpGet]
        public ActionResult EditSubCustomer(int id)
        {
            var subcustomervalue = csm.GetByID(id);
            return View(subcustomervalue);
        }
        [HttpPost]
        public ActionResult EditSubCustomer(SubCustomer p)
        {
            csm.SubCustomerUpdate(p);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteSubCustomer(int id)
        {
            var subcustomervalue = csm.GetByID(id);
            subcustomervalue.SubCustomerStatus = false;
            csm.SubCustomerDelete(subcustomervalue);
            return RedirectToAction("Index");
        }
        
    }
}

DGC2/Views/CustomerSub/AddSubCustomer.cshtml
@model EntityLayer.Concrete.SubCustomer
@{
    ViewBag.Title = "AddSubCustomer";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}
<br />
<h2>Yeni Tedarikçi Ekle</h2>
<a href="/CustomerAppAccept/SubCustomerList/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
<hr />
@using (Html.BeginForm("AddSubCustomer", "CustomerSub", FormMethod.Post))
{
    <div class="form form-group">
        @Html.Label("Kullanıcı Adı")
        @Html.TextBoxFor(x => x.SubCustomerUsername, new { @class = "form-control" })

        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.SubCustomerPassword, new { @class = "form-control" })

        @Html.Label("Şirket İsim")
        @Html.TextBoxFor(x => x.SubCustomerName, new { @class = "form-control" })

        @Html.Label("Şirket Soyisim")
        @Html.TextBoxFor(x => x.SubCustomerSurname, new { @class = "form-control" })

        @Html.Label("Şirket Kodu")
        @Html.TextBoxFor(x => x.SubCustomerCode, new { @class = "form-control" })

        @Html.Label("Şirket Adresi")
        @Html.TextBoxFor(x => x.SubCustomerAddress, new { @class = "form-control" })
        <br />
        <button class="btn btn-info btn-lg btn btn-block">Kaydet</button>
    </div>
}

DGC2/Views/CustomerSub/EditSubCustomer.cshtml
@model EntityLayer.Concrete.SubCustomer
@{
    ViewBag.Title = "EditSubCustomer";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}

<br />
<h2>Tedarikçiyi Düzenle</h2>
<a href="/CustomerAppAccept/SubCustomerList/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
<hr />
@using (Html.BeginForm("EditSubCustomer", "CustomerSub", FormMethod.Post))
{
    <div class="form form-group">
        @Html.Label("Kullanıcı ID")
        @Html.TextBoxFor(x => x.SubCustomerID, new { @class = "form-control" })
        @Html.Label("Kullanıcı Adı")
        @Html.TextBoxFor(x => x.SubCustomerUsername, new { @class = "form-control" })

        <br /> <br />
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.SubCustomerPassword, new { @class = "form-control" })
        <br /> <br />
        @Html.Label("Şirket İsim")
        @Html.TextBoxFor(x => x.SubCustomerName, new { @class = "form-control" })
        <br /> <br />
        @Html.Label("Şirket Soyisim")
        @Html.TextBoxFor(x => x.SubCustomerSurname, new { @class = "form-control" })
        <br /> <br />
        @Html.Label("Şirket Kodu")
        @Html.TextBoxFor(x => x.SubCustomerCode, new { @class = "form-control" })
        <br /> <br />
        @Html.Label("Şirket Adresi")
        @Html.TextBoxFor(x => x.SubCustomerAddress, new { @class = "form-control" })
        <br /><br />
        @Html.Label("Durum")
        @Html.TextBoxFor(x => x.SubCustomerStatus, new { @class = "form-control" })





        <br /><br />
        <button class="btn btn-success btn-lg btn btn-block">Kaydet</button>
    </div>
}

DGC2/Views/CustomerSub/Index.cshtml
@using EntityLayer.Concrete
@model List<SubCustomer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CustomerAdminLayout.cshtml";
}

<h1>Tedarikçi Oluştur</h1>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Tedarikçi Kullanıcı Adı</th>
        <th>Tedarikçi Şifre</th>
        <th>Tedarikçi İsim</th>
        <th>Tedarikçi Kodu</th>
        <th>Tedarikçi Adresi</th>
        <th>Tedarikçi Durum</th>
        <th>Müşteri</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.SubCustomerID</td>
    <td>@item.SubCustomerUsername</td>
    <td>@item.SubCustomerPassword</td>
    <td>@item.SubCustomerName</td>
    <td>@item.SubCustomerCode</td>
    <td>@item.SubCustomerAddress</td>
    <td>@item.SubCustomerStatus</td>
    <td>@item.CustomerID</td>
    <td><a href="/CustomerSub/EditSubCustomer/@item.SubCustomerID" class="btn btn-warning">Tedarikçiyi Düzenle</a></td>
    <td><a href="/CustomerSub/DeleteSubCustomer/@item.SubCustomerID" class="btn btn-danger">Tedarikçiyi Sil</a></td>
</tr>
    }
</table>
<br />
<a href="/CustomerSub/AddSubCustomer" class="btn btn-info">Yeni Tedarikçi Girişi</a>

DGC2/Views/CustomerSub/ListAppoinments.cshtml
@using EntityLayer.Concrete
@model List<Appointment>

@{
    ViewBag.Title = "ListAppoinments";
    Layout = "~/Views/Shared/_CustomerAdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Tür</th>
        <th>Hacim</th>
        <th>Başlangıç<th>
        <th>Bitiş</th>
        <th>Güncelle</th>
       
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AppointmentLoadType</td>
            <td>@item.AppointmentCapacity</td>
            <td>@item.AppStartDate</td>
            <td>@item.AppFinishDate</td>
            <td>@item.AppointmentStatus</td>
            
            <td><a href="#" class="btn btn-warning">Onayla</a></td>
            <td><a href="#" class="btn btn-danger">İptal Et</a></td>
        </tr>
    }
</table>
<br />