DGC2/Controllers/CustomerAppAcceptController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGC2.Controllers
{
    public class CustomerAppAcceptController : Controller
    {
        // GET: CustomerSubAppAccept
        AppointmentManager am = new AppointmentManager(new EfAppointmentDal());
        CustomerSubManager csm = new CustomerSubManager(new EfCustomerAddSubDal());
        CalendarManager cm = new CalendarManager(new EfCalendarDal());
        SubCustomerManager scm = new SubCustomerManager(new EfSubCustomerDal());
        UserManager um = new UserManager(new EfUserDal());
        Context c = new Context();
        [Authorize]
        public ActionResult Index(string p)
        {
            p = (string)Session["CustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.Customers.Where(x => x.CustomerUsername == p).Select(x => x.CustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);

            var arrayOfValues = csm.GetList();
            ViewBag.arrayOfValues = arrayOfValues;
            var graphicvalue = am.GetBySubCustomer(subCustomerInfo);
            
            return View(graphicvalue);   
        }
        public ActionResult Appointments(string p)
        {
            p = (string)Session["CustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.Customers.Where(x => x.CustomerUsername == p).Select(x => x.CustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var appointmentvalue = am.GetBySubCustomer(subCustomerInfo);

            
            return View(appointmentvalue);
        }
        public ActionResult SubCustomerList(string p)
        {
            p = (string)Session["CustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.Customers.Where(x => x.CustomerUsername == p).Select(x => x.CustomerID).FirstOrDefault();


            var ssubcustomervalue = scm.GetListByID(subCustomerInfo);
            return View(ssubcustomervalue);
        }
        public ActionResult CanceledAppoinments(string p)

        {
            p = (string)Session["CustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.Customers.Where(x => x.CustomerUsername == p).Select(x => x.CustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var appointmentvalue = am.GetBySubCustomer(subCustomerInfo);
            
            return View(appointmentvalue);
        }
        public ActionResult WantsChangeAppoinments(string p)
        {
            p = (string)Session["CustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.SubCustomers.Where(x => x.SubCustomerUsername == p).Select(x => x.SubCustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var appointmentvalue = am.GetBySubCustomer(subCustomerInfo);
            
            return View(appointmentvalue);
        }
        public ActionResult AccesChangeAppointment(int id)
        {
            var appvalue = am.GetByID(id);
            appvalue.AppointmentTrackStatus = 2;
            am.AppointmentUpdate(appvalue);
            return RedirectToAction("Appointments");
        }

        public ActionResult FinishedAppointments(string p)
        {

            p = (string)Session["CustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.Customers.Where(x => x.CustomerUsername == p).Select(x => x.CustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var finishedvalue = am.GetBySubCustomer(subCustomerInfo);
            
            return View(finishedvalue);
        }
        public ActionResult ApplyAppointment(int id)
        {
            /* Randevu Alanı */
            var appvalue = am.GetByID(id);
            var calappid = am.GetByID(id).CalendarID;
            appvalue.AppointmentTrackStatus = 4;
            appvalue.AppClickTime = DateTime.Now;
            am.AppointmentUpdate(appvalue);
            
            /* Randevu Alanı */

            /* Takvim Alanı */
            var calappvalue = cm.GetByID((int)calappid);
            if (appvalue.AppointmentLoadType == "Dökme")
            {
                calappvalue.CLDailyAmount += appvalue.AppointmentCapacity;
            }
            else if (appvalue.AppointmentLoadType == "Palet")
            {
                calappvalue.CLPalletCapacity += appvalue.AppointmentCapacity;
            }
            
            cm.CalendarUpdate(calappvalue);
            /* Takvim Alanı */

            return RedirectToAction("Appointments");
        }
        public ActionResult CancelAppointment(int id)
        {
            /* Randevu Alanı */
            var appvalue = am.GetByID(id);
            //var calid = am.GetByID(id).CalendarID;
            ViewBag.d = appvalue.AppointmentID;
            appvalue.AppointmentTrackStatus = 11;
            appvalue.AppClickTime = DateTime.Now;
            /* Randevu Alanı */

            /* Takvim Alanı */
            //var calvalue = cm.GetByID((int)calid);
            //if(appvalue.AppointmentLoadType == "Dökme")
            //{
            //    calvalue.CLDailyAmount -= appvalue.AppointmentCapacity;
            //}
            //else if(appvalue.AppointmentLoadType =="Palet")
            //{
            //    calvalue.CLPalletCapacity -= appvalue.AppointmentCapacity;
            //}
            
            //cm.CalendarUpdate(calvalue);
            /* Takvim Alanı */

            am.AppointmentDelete(appvalue);
            return RedirectToAction("CanceledAppoinments");
        }

        public ActionResult RefuseChangeAppointment(int id)
        {
            var appvalue = am.GetByID(id);
            appvalue.AppointmentTrackStatus = 4;
            am.AppointmentDelete(appvalue);
            return RedirectToAction("Appointments");
        }
        public ActionResult CancelChangedAppointment(int id)
        {
            var stats = am.GetByID(id).AppointmentUCode;
            var asdd = am.GetByIDForChange(false, stats);
            var dsaa = am.GetByIDForChange(true, stats);
            asdd.AppointmentTrackStatus = 4;
            am.AppointmentUpdate(asdd);
            am.AppointmentCopyDelete(dsaa);
            return RedirectToAction("Appointments");
        }
        public ActionResult ApplyChangedAppointment(Appointment p, int id)
        {
            var stat = am.GetByID(id).AppointmentUCode;
            var asd = am.GetByIDForChange(true, stat);
            var dsa = am.GetByIDForChange(false, stat);
            asd.AppointmentTrackStatus = 4;
            asd.AppointmentStatus = false;
            am.AppointmentUpdate(asd);
            am.AppointmentCopyDelete(dsa);
            return RedirectToAction("Appointments");
        }
        
        [HttpGet]
        public ActionResult ThrowToCancelAppointment(int id)
        {
            
            var app = am.GetByID(id);
            return View(app);
        }

        [HttpPost]
        public ActionResult ThrowToCancelAppointment(Appointment p)
        {
            int tempdata = (int)TempData["cancelid"];
            
            var stats = am.GetByID(tempdata).AppointmentUCode;
            var asdd = am.GetByIDForChange(false, stats);
            var dsaa = am.GetByIDForChange(true, stats);
           asdd.AppointmentTrackStatus = 11;
            asdd.AppointmentCancelComment = p.AppointmentCancelComment;
            
                am.AppointmentUpdate(asdd);
            am.AppointmentCopyDelete(dsaa);
            return RedirectToAction("Appointments");
        }
       
        public ActionResult WaitingAppointments(string p)
        {

            p = (string)Session["CustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.Customers.Where(x => x.CustomerUsername == p).Select(x => x.CustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var waitingvalue = am.GetBySubCustomer(subCustomerInfo);
            
            return View(waitingvalue);
        }
        //public ActionResult CanceledAfterChangedAppointments()
        //{
        //    var waitingvalue = am.GetBySubCustomer();
        //    return View(waitingvalue);
        //}
        public ActionResult AppliedWantsCancelAppointments(string p)
        {
            p = (string)Session["CustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.Customers.Where(x => x.CustomerUsername == p).Select(x => x.CustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var appwcgvalue = am.GetBySubCustomer(subCustomerInfo);
            
            return View(appwcgvalue);
        }
        public ActionResult YesCancel(int id)
        {
            var yescancel = am.GetByID(id);
            yescancel.AppointmentTrackStatus = 11;
            yescancel.AppClickTime = DateTime.Now;
            am.AppointmentUpdate(yescancel);
            return RedirectToAction("Appointments");
        }
        public ActionResult NoCancel(int id)
        {
            var nocancel = am.GetByID(id);
            nocancel.AppointmentTrackStatus = 6;
            nocancel.AppClickTime = DateTime.Now;
            am.AppointmentUpdate(nocancel);
            return RedirectToAction("Appointments");
        }

        // TEDARİKÇİ EKLEME 

DGC2/Views/CustomerAppAccept/AddSubCustomer.cshtml
@model EntityLayer.Concrete.SubCustomer
@{
    ViewBag.Title = "AddSubCustomer";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}

<h2>Tedarikçi Girişi</h2>
<a href="/CustomerAppAccept/SubCustomerList/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
<hr />
@using (Html.BeginForm("AddSubCustomer", "CustomerAppAccept", FormMethod.Post))
{
<div class="form form-group">
    @Html.Label("Kullanıcı Adı")
    @Html.TextBoxFor(x => x.SubCustomerUsername, new { @class = "form-control" })

    @Html.Label("Şifre")
    @Html.TextBoxFor(x => x.SubCustomerPassword, new { @class = "form-control" })

    @Html.Label("Firma")
    @Html.TextBoxFor(x => x.SubCustomerCompany, new { @class = "form-control" })

    @Html.Label("Yetkili İsim")
    @Html.TextBoxFor(x => x.SubCustomerName, new { @class = "form-control" })

    @Html.Label("Yetkili Soyisim")
    @Html.TextBoxFor(x => x.SubCustomerSurname, new { @class = "form-control" })

    @Html.Label("Şirket Kodu")
    @Html.TextBoxFor(x => x.SubCustomerCode, new { @class = "form-control" })

    @Html.Label("Şirket Adresi")
    @Html.TextBoxFor(x => x.SubCustomerAddress, new { @class = "form-control" })
    <br />
    <button class="btn btn-info btn-lg btn btn-block">Kaydet</button>
</div>
}

DGC2/Views/CustomerAppAccept/AddUser.cshtml
@model EntityLayer.Concrete.User
@{
    ViewBag.Title = "AddUser";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}


<h2>Alt Müşteri Aç</h2>

<a href="/CustomerAppAccept/UserList/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
<hr />
@using (Html.BeginForm("AddUser", "CustomerAppAccept", FormMethod.Post))
{
    <div class="form-group">

        @Html.HiddenFor(x => x.UserID, new { @class = "form-control" })
        @Html.Label("Kullanıcı Adı")
        @Html.TextAreaFor(x => x.UserUsername, new { @class = "form-control" })
        @Html.Label("Şifre")
        @Html.TextAreaFor(x => x.UserPassword, new { @class = "form-control" })
        @Html.HiddenFor(x => x.UserCreatedPassword, new { @class = "form-control" })
        @Html.Label("Mail")
        @Html.TextAreaFor(x => x.UserMail, new { @class = "form-control" })
        @Html.Label("Telefon")
        @Html.TextAreaFor(x => x.UserTel, new { @class = "form-control" })
        @Html.Label("Statü")
        @Html.TextAreaFor(x => x.UserStatus, new { @class = "form-control" })
        @Html.Label("Rol")
        @Html.TextAreaFor(x => x.UserRole, new { @class = "form-control" })
        @Html.Label("Müşteri ID")
        @Html.TextAreaFor(x => x.CustomerID, new { @class = "form-control" })
        <br />

        @*<input type="text" name="CustomerID" value="@ViewBag.t" class="form-control"  />*@
        <button class="btn btn-info">Oluştur</button>
    </div>

}

DGC2/Views/CustomerAppAccept/CanceledAfterChangedAppointments.cshtml
@using EntityLayer.Concrete
@model List<Appointment>
@{
    ViewBag.Title = "CanceledAfterChangedAppointments";
    Layout = "~/Views/Shared/_CustomerAdminLayout.cshtml";
}



@*<table class="table table-bordered">
        <tr>
            <th>Firma İsim</th>
            <th>Mal İsim</th>
            <th>Yük Adet</th>
            <th>Giriş Tarihi</th>
            <th>Durum</th>
            <th>Sürücü İsim</th>
        </tr>
        @foreach (var item in Model)
        {
            if (item.AppointmentTrackStatus == 11)
            {
                <tr>

                    <td>@item.SubCustomer.SubCustomerName</td>
                    <td>@item.AppointmentName</td>
                    <td>@item.AppointmentCapacity</td>
                    <td>@item.AppStartDate</td>
                    <td>@item.AppointmentStatus</td>


                </tr>
            }
        }
    </table>*@
<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title" style="font-size:30px; font-weight:700">Değişimden Sonra İptal Edilen Randevular</h3>
                <div class="card-tools">


                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                Firma
                            </th>
                            <th style="width: 12%" class="text-center">
                                Randevu Tarihi
                            </th>
                            <th style="width: 2%">
                                Tür
                            </th>
                            <th style="width: 5%">
                                Yük Cinsi
                            </th>
                            <th style="width: 5%">
                                Kap / Koli
                            </th>
                            <th style="width: 5%">
                               
                            </th>

                            <th style="width: 20%" colspan="2">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.AppointmentTrackStatus == 11)
                            {


                                //if (item.Category.CategoryName == "Tiyatro")
                                //{
                                //    color = "badge badge-warning";
                                //}
                                //if (item.Category.CategoryName == "Spor")
                                //{
                                //    color = "badge badge-success";
                                //}
                                //if (item.Category.CategoryName == "Yazılım")
                                //{
                                //    color = "badge badge-info";
                                //}
                                //if (item.Category.CategoryName == "Yemek")
                                //{
                                //    color = "badge badge-secondary";
                                //}
                                //if (item.Category.CategoryName == "Kitap")
                                //{
                                //    color = "badge badge-danger";
                                //}
                                <tr>
                                    <td style="font-size: 20px; font-weight:800">
                                        @item.SubCustomer.SubCustomerCompany
                                    </td>
                                    <td class="project-state" style="font-size:22px">
                                        @(((DateTime)item.AppStartDate).ToString("dd MMMM"))     @(((DateTime)item.AppStartHour).ToString("hh:mm")) - @(((DateTime)item.Calendar.CLFinishDate).ToString("hh:mm"))     @item.Calendar.CLSlice.ToString() .Dilim
                                    </td>
                                    <td style="font-size: 20px;">
                                        @item.AppointmentLoadType
                                    </td>
                                    <td>
                                        <a style="font-size: 20px;">
                                            @item.AppointmentName
                                        </a>
                                        <br />

                                    </td>
                                    <td>
                                        <ul class="list-inline">
                                            <li class="list-inline-item" style="font-size: 30px; font-weight: 600; ">
                                                @item.AppointmentCapacity
                                            </li>
                                        </ul>
                                    </td>
                                    <td>
                                        <p style="font-weight: 800; font-size: 20px; margin-top: 6%" class="badge badge-warning">Değişimden Sonra İptal Edilmiştir</p>
                                    </td>

                                    <td class="project-actions text-right">
                                    </td>


                                </tr>

                            }
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>

DGC2/Views/CustomerAppAccept/EditUser.cshtml
@model EntityLayer.Concrete.User
@{
    ViewBag.Title = "EditUser";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}

<h2>Alt Müşteri Düzenle</h2>

<a href="/CustomerAppAccept/UserList/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
<hr />
@using (Html.BeginForm("EditUser", "CustomerAppAccept", FormMethod.Post))
{
    <div class="form-group">

        @Html.HiddenFor(x => x.UserID, new { @class = "form-control" })
        @Html.Label("Kullanıcı Adı")
        @Html.TextAreaFor(x => x.UserUsername, new { @class = "form-control" })
        @Html.Label("Şifre")
        @Html.TextAreaFor(x => x.UserPassword, new { @class = "form-control" })
        @Html.HiddenFor(x => x.UserCreatedPassword, new { @class = "form-control" })
        @Html.Label("Mail")
        @Html.TextAreaFor(x => x.UserMail, new { @class = "form-control" })
        @Html.Label("Telefon")
        @Html.TextAreaFor(x => x.UserTel, new { @class = "form-control" })
        @Html.Label("Statü")
        @Html.TextAreaFor(x => x.UserStatus, new { @class = "form-control" })
        @Html.Label("Rol")
        @Html.TextAreaFor(x => x.UserRole, new { @class = "form-control" })
        @Html.Label("Müşteri ID")
        @Html.TextAreaFor(x => x.CustomerID, new { @class = "form-control" })
        <br />

        @*<input type="text" name="CustomerID" value="@ViewBag.t" class="form-control"  />*@
        <button class="btn btn-info">Oluştur</button>
    </div>

}

DGC2/Views/CustomerAppAccept/SeeAndCancelTheAppointment.cshtml
@model EntityLayer.Concrete.Appointment
@{
    ViewBag.Title = "SeeAndCancelTheAppointment";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}
@*<h2><b>(Yeni)@ViewBag.company</b> - @ViewBag.name - <b>@ViewBag.capacity</b></h2>*@
@*<hr />*@
@*<h2><b>(Eski)@ViewBag.company</b> - @ViewBag.oldname - <b>@ViewBag.oldcapacity</b></h2>*@
<a href="/CustomerAppAccept/WantsChangeAppoinments/" class="closepopup"><i class="fas fa-minus-circle"></i></a>

@using (Html.BeginForm("SeeAndCancelTheAppointment", "CustomerAppAccept", FormMethod.Post))
{
<div class="form-group">

    @Html.HiddenFor(x => x.AppointmentTrackStatus)
    @Html.HiddenFor(x => x.AppointmentID)
    @Html.HiddenFor(x => x.AppointmentLoadType)
    @Html.HiddenFor(x => x.DriverID)
    @Html.HiddenFor(x => x.SubCustomerID)
    @Html.HiddenFor(x => x.AppointmentStatus)
    @Html.HiddenFor(x => x.ChiefID)
    @Html.HiddenFor(x => x.DownloadedDate)
    @Html.HiddenFor(x => x.AppointmentImage)
    @Html.HiddenFor(x => x.AppointmentComment)
    @Html.HiddenFor(x => x.AppointmentName)
    @Html.HiddenFor(x => x.AppFinishDate)
    @Html.HiddenFor(x => x.InComingDate)
    @Html.HiddenFor(x => x.AppointmentUCode)
    @Html.HiddenFor(x => x.AppointmentLoadType, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppointmentCapacity, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppStartDate, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppStartDate)
    @Html.HiddenFor(x => x.CalendarID)
    @Html.HiddenFor(x => x.AppointmentUpdateComment)
    @Html.HiddenFor(x => x.AppStartHour)
    @Html.HiddenFor(x => x.AppClickTime)

    <h3 style="text-align:center">Eski Randevu</h3>
    <div style="text-align: center; background-color: red; color: white; margin-bottom: 25px; margin-top: 25px; font-size: 30px; border-radius: 10px "><b>@ViewBag.company</b> - @ViewBag.oldname - <b>@ViewBag.oldcapacity</b></div>
    <h3 style="text-align:center">Yeni Randevu</h3>
    <div style="text-align: center; background-color: forestgreen; color: white; margin-bottom: 25px; margin-top: 25px; font-size: 30px; border-radius: 10px "><b>@ViewBag.company</b> - @ViewBag.name - <b>@ViewBag.capacity</b></div>

    @Html.HiddenFor(x => x.AppointmentCancelComment, new { @class = "form-control" })
    <br />

    <a href="/CustomerAppAccept/ApplyChangedAppointment/@ViewBag.a" class="btn btn-success btn-lg btn btn-block">Randevuyu Onayla</a>
    <a href="/CustomerAppAccept/ThrowToCancelAppointment/@ViewBag.a" class="btn btn-danger btn-lg btn btn-block">Randevuyu İptal Et</a>


</div>
}

DGC2/Views/CustomerAppAccept/SeeTheAppointment.cshtml
@model EntityLayer.Concrete.Appointment

@{
    ViewBag.Title = "SeeTheAppointment";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}

<h2><b>@ViewBag.company</b> - @ViewBag.name - <b>@ViewBag.capacity</b></h2>
<a href="/CustomerAppAccept/WantsChangeAppoinments/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
<hr />
 
@using (Html.BeginForm("SeeTheAppointment", "CustomerAppAccept", FormMethod.Post))
{
<div class="form-group">

    @Html.HiddenFor(x => x.AppointmentTrackStatus)
    @Html.HiddenFor(x => x.AppointmentID)
    @Html.HiddenFor(x => x.AppointmentLoadType)
    @Html.HiddenFor(x => x.DriverID)
    @Html.HiddenFor(x => x.SubCustomerID)
    @Html.HiddenFor(x => x.AppointmentStatus)
    @Html.HiddenFor(x => x.ChiefID)
    @Html.HiddenFor(x => x.DownloadedDate)
    @Html.HiddenFor(x => x.AppointmentImage)
    @Html.HiddenFor(x => x.AppointmentComment)
    @Html.HiddenFor(x => x.AppointmentName)
    @Html.HiddenFor(x => x.AppFinishDate)
    @Html.HiddenFor(x => x.InComingDate)
    @Html.HiddenFor(x => x.AppointmentUCode)
    @Html.HiddenFor(x => x.AppointmentLoadType, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppointmentCapacity, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppStartDate, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppStartDate)
    @Html.HiddenFor(x => x.CalendarID)

    @Html.TextAreaFor(x => x.AppointmentUpdateComment, new { @class = "form-control", @readonly = "readonly" })
    <br />
    <a href="/CustomerAppAccept/AccesChangeAppointment/@ViewBag.a" class="btn btn-success btn-lg btn btn-block">Düzenlemeye Onay Ver</a>
    <a href="/CustomerAppAccept/RefuseChangeAppointment/@ViewBag.a" class="btn btn-danger btn-lg btn btn-block">Düzenlemeyi İsteğini Reddet</a>

</div>
}

DGC2/Views/CustomerAppAccept/ThrowToCancelAppointment.cshtml
@model EntityLayer.Concrete.Appointment
@{
    ViewBag.Title = "ThrowToCancelAppointment";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}
@*<h2><b>(Yeni)@ViewBag.company</b> - @ViewBag.name - <b>@ViewBag.capacity</b></h2>*@
@*<hr />*@
@*<h2><b>(Eski)@ViewBag.company</b> - @ViewBag.oldname - <b>@ViewBag.oldcapacity</b></h2>*@
<a href="/CustomerAppAccept/WantsChangeAppoinments/" class="closepopup"><i class="fas fa-minus-circle"></i></a>

@using (Html.BeginForm("ThrowToCancelAppointment", "CustomerAppAccept", FormMethod.Post))
{
<div class="form-group">

    @Html.HiddenFor(x => x.AppointmentTrackStatus)
    @Html.HiddenFor(x => x.AppointmentID)
    @Html.HiddenFor(x => x.AppointmentLoadType)
    @Html.HiddenFor(x => x.DriverID)
    @Html.HiddenFor(x => x.SubCustomerID)
    @Html.HiddenFor(x => x.AppointmentStatus)
    @Html.HiddenFor(x => x.ChiefID)
    @Html.HiddenFor(x => x.DownloadedDate)
    @Html.HiddenFor(x => x.AppointmentImage)
    @Html.HiddenFor(x => x.AppointmentComment)
    @Html.HiddenFor(x => x.AppointmentName)
    @Html.HiddenFor(x => x.AppFinishDate)
    @Html.HiddenFor(x => x.InComingDate)
    @Html.HiddenFor(x => x.AppointmentUCode)
    @Html.HiddenFor(x => x.AppointmentLoadType, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppointmentCapacity, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppStartDate, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppStartDate)
    @Html.HiddenFor(x => x.CalendarID)
    @Html.HiddenFor(x => x.AppointmentUpdateComment)
    @Html.HiddenFor(x => x.AppStartHour)
    @Html.HiddenFor(x => x.AppClickTime)
    <h3 style="text-align:center">Eski Randevu</h3>
    <div style="text-align: center; background-color: red; color: white; margin-bottom: 25px; margin-top: 25px; font-size: 30px; border-radius: 10px "><b>@ViewBag.company</b> - @ViewBag.oldname - <b>@ViewBag.oldcapacity</b></div>
    <h3 style="text-align:center">Yeni Randevu</h3>
    <div style="text-align: center; background-color: forestgreen; color: white; margin-bottom: 25px; margin-top: 25px; font-size: 30px; border-radius: 10px "><b>@ViewBag.company</b> - @ViewBag.name - <b>@ViewBag.capacity</b></div>
    @Html.Label("İptal Edilme Nedeni")
    @Html.TextAreaFor(x => x.AppointmentCancelComment, new { @class = "form-control" })
    <br />


    <button class="btn btn-danger btn-lg btn btn-block">Randevuyu İptal Et</button>


</div>
}