DGC2/Controllers/SubCustomerController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;



namespace DGC2.Controllers
{
    public class SubCustomerController : Controller
    {
        // GET: SubCustomer

        SubCustomerManager scm = new SubCustomerManager(new EfSubCustomerDal());
        AppointmentManager apm = new AppointmentManager(new EfAppointmentDal());
        CalendarManager cm = new CalendarManager(new EfCalendarDal());
        DriverManager dm = new DriverManager(new EfDriverDal());


        [Authorize]
        public ActionResult Index(string p)
        {
            p = (string)Session["SubCustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.SubCustomers.Where(x => x.SubCustomerUsername == p).Select(x => x.SubCustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var graphicResult = apm.GetBySubCustomerID(subCustomerInfo);
            return View(graphicResult);

        }
        [HttpGet]
        public ActionResult AddDriver()
        {

            return View();


        }
        [HttpPost]
        public ActionResult AddDriver(Driver p, Appointment ps)
        {

            p.DriverName = "Mahmut";
            //p.DriverSurname = "Özcan";
            p.DriverNumber = "321321321";
            p.DriverPlate = "34 ASD 23";
            p.DriverLogisticName = "React A.Ş.";
            var name = p.DriverName;
            //var surname = p.DriverSurname;
            var number = p.DriverNumber;
            var plate = p.DriverPlate;
            var logisticname = p.DriverLogisticName;
            var app = apm.GetByID(78);
            //ps.AppointmentComment =p.DriverName + " " + p.DriverSurname + " " + p.DriverNumber + " " + p.DriverPlate + " " + p.DriverLogisticName;
            //scm.DriverAdd(p);

            var fullname = String.Format("İsim:" + name + " Soyad:" + " Telefon:" + number + " Plaka:" + plate + " Firma:" + logisticname);
            var asd = apm.GetByID(78);
            asd.AppointmentComment = fullname;

            //apm.AppointmentUpdate(app);
            return RedirectToAction("Index");
        }
        //[HttpGet]
        //public ActionResult EditDriver(int id)
        //{


        //    var drivervalue = scm.GetByID(id);
        //    return View(drivervalue);
        //}
        //[HttpPost]
        //public ActionResult EditDriver(Driver p)
        //{

        //    scm.DriverUpdate(p);
        //    return RedirectToAction("Index");
        //}
        //public ActionResult DeleteDriver(int id)
        //{
        //    var drivervalue = scm.GetByID(id);
        //    drivervalue.DriverStatus = false;
        //    scm.DriverUpdate(drivervalue);
        //    return RedirectToAction("Index");
        //}


        public ActionResult WaitingListAppoinment(string p)
        {
            p = (string)Session["SubCustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.SubCustomers.Where(x => x.SubCustomerUsername == p).Select(x => x.SubCustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var listappoinment = apm.GetBySubCustomerID(subCustomerInfo);

            return View(listappoinment);

        }
        public ActionResult AskChangeList(string p)
        {
            p = (string)Session["SubCustomerUsername"];
            Context c = new Context();
            var subCustomerInfo = c.SubCustomers.Where(x => x.SubCustomerUsername == p).Select(x => x.SubCustomerID).FirstOrDefault();

            //var graphicresult = apm.GetList().Where(x=>x.SubCustomerID == subCustomerInfo);
            var listappoinment = apm.GetBySubCustomerID(subCustomerInfo);

            return View(listappoinment);

        }

        [HttpGet]
        public ActionResult AskChangeComment(int id)
        {


            var askvalue = apm.GetByID(id);
            askvalue.AppointmentUpdateComment = null;
            askvalue.AppointmentStatus = false;
            return View(askvalue);
        }
        [HttpPost]
        public ActionResult AskChangeComment(Appointment p)
        {

            if (p.AppointmentTrackStatus == 4)
            {

                p.AppointmentTrackStatus = 20;
            }

            p.AppointmentStatus = false;
            apm.AppointmentUpdate(p);
            return RedirectToAction("AppliedListAppoinment");
        }

        [HttpGet]
        public ActionResult EditAskChange(int id)
        {


            var askvalue = apm.GetByID(id);
            TempData["oldvalue"] = askvalue.AppointmentID;
            return View(askvalue);
        }
        [HttpPost]
        public ActionResult EditAskChange(Appointment p)
        {

            var oldvalue = apm.GetByID((int)TempData["oldvalue"]);


            oldvalue.AppointmentTrackStatus = 0;
            p.AppStartDate = oldvalue.AppStartDate;
            apm.AppointmentUpdate(oldvalue);

            if (p.AppointmentStatus == false)
                p.AppointmentStatus = true;
            if (p.AppointmentTrackStatus == 4)
                p.AppointmentTrackStatus = 24;


            apm.AppointmentAdd(p);
            return RedirectToAction("AppliedListAppoinment");
        }


        [HttpGet]
        public ActionResult EditNotAppliedAppointment(int id)
        {
            var subcustomervalue = apm.GetByID(id);
            var idvalue = subcustomervalue.AppointmentID;
            TempData["OldSlice"] = subcustomervalue.AppSlice;
            TempData["OldStartDate"] = subcustomervalue.AppStartDate;

            TempData["OldCalendarID"] = subcustomervalue.CalendarID;
            var editDateTime = subcustomervalue.AppStartDate;
            DateTime NewDT = Convert.ToDateTime(editDateTime);
            var parsedDateTime = DateTime.Parse(NewDT.ToShortDateString());
            ViewBag.parsedDateTime = parsedDateTime.ToString("yyyy-MM-dd");

            ViewBag.editnot = subcustomervalue.AppSlice;

            List<SelectListItem> valuecm = (from x in cm.GetList()
                                            select new SelectListItem
                                            {
                                                Text = x.CLSlice.ToString(),
                                                Value = x.CalendarID.ToString()
                                            }).ToList();
            ViewBag.vlc = valuecm;
            return View(subcustomervalue);
        }
        [HttpPost]
        public ActionResult EditNotAppliedAppointment(Appointment p, Calendar k, string dateee)
        {

            //var oldAppCalendarID = apm.GetByID((int)TempData["OldCalendarID"]);

            var oldAppCalendarID = cm.GetByID((int)TempData["OldCalendarID"]);
            string oldStartDate = (string)TempData["OldStartDate"];
            int oldSlice = (int)TempData["OldSlice"];
            DateTime stdate = Convert.ToDateTime(p.AppStartDate);
            DateTime dt = DateTime.Parse(stdate.ToLongDateString());
            string searchdate = dt.ToString("dd MMMM");

            var newcalendarid = c.Calendars.Where(c => c.CLStartDate == searchdate && c.CLSlice == p.AppSlice).Select(c => c.CalendarID).FirstOrDefault();

            if (oldStartDate != p.AppStartDate) // Gün Değişirse
            {
                p.CalendarID = newcalendarid;
                var newcl = cm.GetByID(newcalendarid);
                if (p.AppointmentLoadType == "Dökme")
                {
                    oldAppCalendarID.CLDailyAmount -= p.AppointmentCapacity;
                    newcl.CLDailyAmount += p.AppointmentCapacity;

                }
                else if (p.AppointmentLoadType == "Palet")
                {
                    oldAppCalendarID.CLDailyPaletAmount -= p.AppointmentCapacity;
                    newcl.CLPalletCapacity += p.AppointmentCapacity;
                }

                p.AppStartDate = dt.ToString("dd MMMM");
                cm.CalendarUpdate(oldAppCalendarID);
                cm.CalendarUpdate(newcl);

            }
            else if (oldSlice != p.AppSlice) // Dilim Değişirse
            {
                var newslice = c.Calendars.Where(c => c.CLSlice == p.AppSlice).Select(c => c.CalendarID).FirstOrDefault();
                var justslice = cm.GetByID(newslice);
                p.CalendarID = newslice;

                if (p.AppointmentLoadType == "Dökme")
                {
                    oldAppCalendarID.CLDailyAmount -= p.AppointmentCapacity;
                    justslice.CLDailyAmount += p.AppointmentCapacity;


                }
                else if (p.AppointmentLoadType == "Palet")
                {
                    oldAppCalendarID.CLDailyPaletAmount -= p.AppointmentCapacity;
                    justslice.CLPalletCapacity += p.AppointmentCapacity;
                }
                cm.CalendarUpdate(oldAppCalendarID);
                cm.CalendarUpdate(justslice);
            }
            else if (oldStartDate != p.AppStartDate
                && oldSlice != p.AppSlice) // Dilim ve Gün Değişirse
            {

                p.CalendarID = newcalendarid;
                var newcl = cm.GetByID(newcalendarid);
                if (p.AppointmentLoadType == "Dökme")
                {
                    oldAppCalendarID.CLDailyAmount -= p.AppointmentCapacity;
                    newcl.CLDailyAmount += p.AppointmentCapacity;

                }
                else if (p.AppointmentLoadType == "Palet")
                {
                    oldAppCalendarID.CLDailyPaletAmount -= p.AppointmentCapacity;
                    newcl.CLPalletCapacity += p.AppointmentCapacity;
                }


                p.CalendarID = newcalendarid;

DGC2/Views/SubCustomer/AddDriver.cshtml
@model EntityLayer.Concrete.Driver
@{
    ViewBag.Title = "AddDriver";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}

<br />
<h2>Yeni Sürücü Ekleme Sayfası</h2>

@using (Html.BeginForm("AddDriver", "SubCustomer", FormMethod.Post))
{

<div class="card-form">
    <a href="kapat">content</a>
    <div class="form-group">
        @Html.Label("Sürücü İsim")
        @Html.TextBoxFor(x => x.DriverName, new { @class = "form-control" })
        <br />
        @Html.Label("Sürücü Soyisim")
        @Html.TextBoxFor(x => x.DriverSurname, new { @class = "form-control" })
        <br />
        @Html.Label("Statü")
        @Html.TextBoxFor(x => x.DriverStatus, new { @class = "form-control" })
        <br />
        @Html.Label("Çalıştığı Firma")
        @Html.TextBoxFor(x => x.DriverLogisticName, new { @class = "form-control" })
        <br />
        @Html.Label("Plaka")
        @Html.TextBoxFor(x => x.DriverPlate, new { @class = "form-control" })
        <br />
        @Html.Label("Telefon Numarası")
        @Html.TextBoxFor(x => x.DriverNumber, new { @class = "form-control" })
        <br />
        @Html.Label("ID")
        @Html.TextBoxFor(x => x.SubCustomerID, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary btn-lg btn-block">Kaydet</button>
    </div>
</div>
        }

DGC2/Views/SubCustomer/AskChangeComment.cshtml
@model EntityLayer.Concrete.Appointment
@{
    ViewBag.Title = "AskChangeComment";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}

<h2>Değişiklik Talebi Formu</h2>
<a href="/SubCustomer/AppliedAppoinments/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
<hr />
@using (Html.BeginForm("AskChangeComment", "SubCustomer", FormMethod.Post))
{
<div class="form-group">

    @Html.HiddenFor(x => x.AppointmentTrackStatus)
    @Html.HiddenFor(x => x.AppointmentID)
    @Html.HiddenFor(x => x.AppointmentLoadType)
    @Html.HiddenFor(x => x.DriverID)
    @Html.HiddenFor(x => x.SubCustomerID)
    @Html.HiddenFor(x => x.AppointmentStatus)
    @Html.HiddenFor(x => x.ChiefID)
    @Html.HiddenFor(x => x.DownloadedDate)
    @Html.HiddenFor(x => x.AppointmentImage)
    @Html.HiddenFor(x => x.AppointmentComment)
    @Html.HiddenFor(x => x.AppointmentName)
    @Html.HiddenFor(x => x.AppFinishDate)
    @Html.HiddenFor(x => x.InComingDate)
    @Html.HiddenFor(x => x.AppointmentUCode)
    @Html.HiddenFor(x => x.AppointmentLoadType, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppointmentCapacity, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppStartDate, new { @class = "form-control" })
    @Html.HiddenFor(x => x.AppStartDate)
    @Html.HiddenFor(x => x.CalendarID)
    @Html.HiddenFor(x => x.AppointmentCancelComment)

    @Html.Label("Değişiklik Nedeni")
    @Html.TextAreaFor(x => x.AppointmentUpdateComment, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary btn-lg btn btn-block">Gönder</button>
</div>
}

DGC2/Views/SubCustomer/AskChangeList.cshtml
@using EntityLayer.Concrete
@model List<Appointment>
@{
    ViewBag.Title = "AskChangeList";
    Layout = "~/Views/Shared/_SubCustomerLayout.cshtml";
}

@*<table class="table table-bordered">
    <tr>
        <th>Firma İsim</th>
        <th>Mal İsim</th>
        <th>Yük Adet</th>
        <th>Giriş Tarihi</th>
        <th>Durum</th>
        <th>Sürücü İsim</th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.AppointmentTrackStatus == 2)
        {
            <tr>

                
                <td>@item.SubCustomer.Customer.CompanyName</td>
                <td>@item.AppointmentName</td>
                <td>@item.AppointmentCapacity</td>
                <td>@item.AppStartDate</td>
                <td>@item.AppointmentStatus</td>
                
                <td><a href="/SubCustomer/EditAskChange/@item.AppointmentID" class="btn btn-info">Düzenle</a></td>

            </tr>
        }
    }
</table>*@
<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title" style="font-size:30px; font-weight:700">Değişiklik Talebi</h3>
                <div class="card-tools">
                    

                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 8%">
                                Tür
                            </th>
                            <th style="width: 15%">
                                Yük Cinsi
                            </th>
                            <th style="width: 15%">
                                Kap / Koli
                            </th>
                            <th style="width: 10%">
                                
                            </th>
                            <th style="width: 12%" class="text-center">
                                Geliş Tarihi
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.AppointmentTrackStatus == 2)
                            {


                                //if (item.Category.CategoryName == "Tiyatro")
                                //{
                                //    color = "badge badge-warning";
                                //}
                                //if (item.Category.CategoryName == "Spor")
                                //{
                                //    color = "badge badge-success";
                                //}
                                //if (item.Category.CategoryName == "Yazılım")
                                //{
                                //    color = "badge badge-info";
                                //}
                                //if (item.Category.CategoryName == "Yemek")
                                //{
                                //    color = "badge badge-secondary";
                                //}
                                //if (item.Category.CategoryName == "Kitap")
                                //{
                                //    color = "badge badge-danger";
                                //}
                                <tr>
                                    <td style="font-size: 20px;">
                                        @item.AppointmentLoadType
                                    </td>
                                    <td>
                                        <a style="font-size: 20px;">
                                            @item.AppointmentName
                                        </a>
                                        <br />

                                    </td>
                                    <td>
                                        <ul class="list-inline">
                                            <li class="list-inline-item" style="font-size: 30px; font-weight: 600; ">
                                                @item.AppointmentCapacity
                                            </li>
                                        </ul>
                                    </td>
                                    <td>
                                        <p style="font-weight:800; font-size:20px" class="badge badge-dark">Talep Onaylandı</p>
                                    </td>
                                    <td class="project-state" style="font-size:18px">
                                        @(((DateTime)item.AppStartDate).ToString("dd MMMM")) @(((DateTime)item.AppStartHour).ToString("hh:mm"))  @item.Calendar.CLSlice.ToString() .Dilim
                                    </td>
                                    <td class="project-actions text-right">
                                    </td>
                                    <td><a href="/SubCustomer/EditAskChange/@item.AppointmentID" class="btn btn-primary">Randevuyu Düzenle</a></td>

                                </tr>

                            }
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>

DGC2/Views/SubCustomer/EditDriver.cshtml
@model EntityLayer.Concrete.Driver
@{
    ViewBag.Title = "EditDriver";
    Layout = "~/Views/Shared/_SubCustomerLayout.cshtml";
}

<h2>Sürücü Düzenleme Sayfası</h2>

@using (Html.BeginForm("EditDriver", "SubCustomer", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("ID")
    @Html.TextBoxFor(x => x.DriverID, new { @class = "form-control" })
    <br />
    @Html.Label("Sürücü İsim")
    @Html.TextBoxFor(x => x.DriverName, new { @class = "form-control" })
    <br />
    @Html.Label("Sürücü Soyisim")
    @Html.TextBoxFor(x => x.DriverSurname, new { @class = "form-control" })
    <br />
    @Html.Label("Statü")
    @Html.TextBoxFor(x => x.DriverStatus, new { @class = "form-control" })
    <br />
    @Html.Label("Çalıştığı Firma")
    @Html.TextBoxFor(x => x.DriverLogisticName, new { @class = "form-control" })
    <br />
    @Html.Label("Plaka")
    @Html.TextBoxFor(x => x.DriverPlate, new { @class = "form-control" })
    <br />
    @Html.Label("Telefon Numarası")
    @Html.TextBoxFor(x => x.DriverNumber, new { @class = "form-control" })
    <br />
    @Html.Label("Tedarikçi ID")
    @Html.TextBoxFor(x => x.SubCustomerID, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</div>
}

DGC2/Views/SubCustomer/EditNotAppliedAppointment.cshtml
@model EntityLayer.Concrete.Appointment
@{
    ViewBag.Title = "EditNotAppliedAppointment";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>

    <script src="~/Scripts/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script src="~/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="~/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
</head>
<body>

    <h2>Randevuyu Düzenle</h2>

    <a href="/SubCustomer/AppliedListAppoinment/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
    <hr />

    @using (Html.BeginForm("EditNotAppliedAppointment", "SubCustomer", FormMethod.Post))
    {
        <div class="form-group">




            <div class="container">
                <div class="row">
                    <div class="col text-center">
                        <br /><h3 style="font-weight:600">Açıklama</h3>
                        <hr />
                        <h5 style="font-weight:600; text-align:right" class="mt-3">Tarih</h5><br />
                        <br />

                        <h5 style="font-weight:600; text-align:right">Dilim</h5><br />
                        <h5 style="font-weight:600; text-align:right" class="mt-3">Yük Cinsi</h5><br />
                        <h5 style="font-weight:600; text-align:right"class="mt-3">Tür</h5><br />
                        <h5 style="font-weight:600; text-align:right"class="mt-2">Kap / Koli</h5><br />
                        <h5 style="font-weight:600; text-align:right"class="mt-2">Sürücü İsim</h5><br />
                        <h5 style="font-weight:600; text-align:right"class="mt-3">Sürücü Telefon</h5><br />
                        <h5 style="font-weight:600; text-align:right"class="mt-3">Sürücü Plaka</h5><br />
                        <h5 style="font-weight:600; text-align:right"class="mt-3">Sürücü Firma</h5><br />


                    </div>
                    <div class="col text-center">
                        <br /> <h3 style="font-weight:600">Eski Randevu</h3>
                        <hr />
                        <input class="form-control "  readonly placeholder="Tarih" value="@(Model.AppStartDate)" />
                        <br />

                        <input type="text" class="form-control" readonly placeholder="Eski Dilim" value="@Model.AppSlice"><br />
                        <input type="text" class="form-control" readonly placeholder="Yük Cinsi" value="@Model.AppointmentName"><br />
                        <input type="text" class="form-control" readonly placeholder="Tür" value="@Model.AppointmentLoadType"><br />
                        <input type="text" class="form-control" readonly placeholder="Kap / Koli" value="@Model.AppointmentCapacity"><br />
                        <input type="text" class="form-control" readonly placeholder="Sürücü İsim" value="@Model.AppDriverName"><br />
                        <input type="text" class="form-control" readonly placeholder="Sürücü Telefon" value="@Model.AppDriverNumber"><br />
                        <input type="text" class="form-control" readonly placeholder="Sürücü Plaka" value="@Model.AppDriverPlate"><br />
                        <input type="text" class="form-control" readonly placeholder="Sürücü Firma" value="@Model.AppDriverLogisticName">
                    </div>
                    <div class="col text-center">
                        <br /><h3 style="font-weight:600">Yeni Randevu</h3>
                        <hr />
                        <input type="date" id="date" name="AppStartDate" class="form-control " value="@ViewBag.parsedDateTime" placeholder="dd-MMMM" min="@DateTime.Now.ToString("yyyy-MM-dd")" max="@DateTime.Now.AddDays(7).ToString("yyyy-MM-dd")" />
                        <br />
                        
                        <input type="text" id="text" class="form-control" name="AppSlice" placeholder="Dilim" value="@Model.AppSlice"><br />
                        <input type="text" id="text" class="form-control" name="AppointmentName" placeholder="Yük Cinsi" value="@Model.AppointmentName"><br />
                        <input type="text" id="text" class="form-control" name="AppointmentLoadType" placeholder="Tür" value="@Model.AppointmentLoadType"><br />
                        <input type="text" id="text" class="form-control" name="AppointmentCapacity" placeholder="Kap / Koli" value="@Model.AppointmentCapacity"><br />
                        <input type="text" id="text" class="form-control" name="AppDriverName" placeholder="Sürücü İsim" value="@Model.AppDriverName"><br />
                        <input type="text" id="text" class="form-control" name="AppDriverNumber" placeholder="Sürücü Telefon" value="@Model.AppDriverNumber"><br />
                        <input type="text" id="text" class="form-control" name="AppDriverPlate" placeholder="Sürücü Plaka" value="@Model.AppDriverPlate"><br />
                        <input type="text" id="text" class="form-control" name="AppDriverLogisticName" placeholder="Sürücü Firma" value="@Model.AppDriverLogisticName">
                    </div>


                </div>
            </div>


            @Html.HiddenFor(x => x.CalendarID)

            @Html.HiddenFor(x => x.AppointmentTrackStatus)
            @Html.HiddenFor(x => x.AppointmentID)
            @Html.HiddenFor(x => x.AppointmentLoadType)
            @Html.HiddenFor(x => x.DriverID)
            @Html.HiddenFor(x => x.SubCustomerID)
            @Html.HiddenFor(x => x.AppointmentStatus)
            @Html.HiddenFor(x => x.ChiefID)
            @Html.HiddenFor(x => x.DownloadedDate)
            @Html.HiddenFor(x => x.AppointmentImage)
            @Html.HiddenFor(x => x.AppointmentComment)

            @Html.HiddenFor(x => x.AppFinishDate)
            @Html.HiddenFor(x => x.InComingDate)
            @Html.HiddenFor(x => x.AppointmentUCode)
            @Html.HiddenFor(x => x.AppointmentUpdateComment)
            @*@Html.HiddenFor(x => x.CalendarID)*@
            @Html.HiddenFor(x => x.AppStartHour)
            @*@Html.HiddenFor(x => x.AppStartDate)*@
            @Html.HiddenFor(x => x.AppointmentCancelComment)
            @Html.HiddenFor(x => x.AppointmentLoadType)
            @Html.HiddenFor(x => x.AppClickTime)
            @*@Html.Label("Kap / Koli")
            @Html.TextBoxFor(x => x.AppointmentCapacity, new { @class = "form-control" })
            @Html.HiddenFor(x => x.AppClickTime)
            @Html.Label("Yük Cinsi")
            @Html.TextBoxFor(x => x.AppointmentName, new { @class = "form-control" })
            @Html.Label("Sürücü İsim")
            @Html.TextBoxFor(x => x.AppDriverName, new { @class = "form-control" })
            @Html.Label("Sürücü Telefon")
            @Html.TextBoxFor(x => x.AppDriverNumber, new { @class = "form-control" })
            @Html.Label("Plaka")
            @Html.TextBoxFor(x => x.AppDriverPlate, new { @class = "form-control" })
            @Html.Label("Sürücü Firma")
            @Html.TextBoxFor(x => x.AppDriverLogisticName, new { @class = "form-control" })
            @Html.DropDownListFor(x => x.CalendarID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })*@




            <br />

            <p style="font-size:20px">
                * Randevu Onaylanana kadar randevu içeriği değiştirilebilir. Randevu Onaylandıktan sonra
                miktar ve zamanla ilgili değişiklik <u>yapılamaz</u>.
            </p>


            <br />
            <button id="press" class="btn btn-success btn-lg btn btn-block">Kaydet</button>
        </div>


    }

@*<script type="text/javascript">
    $(document).ready(function () {

             $('#press').click(function () {
                 var Datee = new Date($('#out').datepicker().val());
                 var dateee = Datee.toDateString();
                 
                    //var newDate = moment(Datee).format('M/D/YYYY h:mm:ss A');
                    //var newDaTe = new String(Datee);

                    $.post('@Url.Action("editnotappliedappointment", "subcustomer")',

                        { dateee: dateee });

                });
        })

</script>*@
    @*<script type="text/javascript">
            $(document).ready(function () {
                $("#in").on('change', function () {
                    var days = +$(this).val();
                    var actualDate = new Date();
                    actualDate.setDate(actualDate.getDate() + days);
                    console.log(days, actualDate);

                    $('#out').datepicker("setDate", actualDate);
                    /*var ShortDate = $('#out').datepicker({ dateFormat: 'dd-mm-yy' }).val();*/
                   /* $("#demo").html(ActualDate);*/
                });

                $('#out').datepicker().on('change focus blur click', function (event) {

                    /* $(".ui-datepicker-calendar").hide();*/
                    $(".ui-datepicker").hide();
                    dateFormat: 'dd/mm/yyyy';

                });
                /*2022 - 03 - 08 00: 00: 00.000*/
                $('#press').click(function () {
                    var Datee = new Date($('#out').datepicker('getDate'));
                    var dateee = $('#in').val();
                    //var newDate = moment(Datee).format('M/D/YYYY h:mm:ss A');
                    //var newDaTe = new String(Datee);

                    $.post('@Url.Action("editnotappliedappointment", "subcustomer")',

                        { dateee: dateee });

                });

            });

        </script>*@


</body>
</html>