DGC2/Controllers/AdminChiefController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGC2.Controllers
{
    public class AdminChiefController : Controller
    {
        // GET: AdminChief
        ChiefManager cm = new ChiefManager(new EfChiefDal());
        public ActionResult Index()
        {
            var chiefvalues = cm.GetList();
            return View(chiefvalues);
        }
        [HttpGet]
        public ActionResult AddChief()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddChief(Chief p)
        {
            p.ChiefStartDate = DateTime.Parse(DateTime.Now.ToShortTimeString());
            p.ChiefFinishDate = DateTime.Parse(DateTime.Now.ToShortTimeString());


            cm.ChiefAdd(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditChief(int id)
        {
            var chiefvalues = cm.GetByID(id);
            return View(chiefvalues);
        }
        [HttpPost]
        public ActionResult EditChief(Chief p)
        {
            cm.ChiefUpdate(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteChief(int id)
        {//Güncelleme işlemi
            //customer delete kısmına git
            var chiefvalue = cm.GetByID(id);
            chiefvalue.ChiefStatus = false;
            cm.ChiefDelete(chiefvalue);
            return RedirectToAction("Index");
        }
    }
}

DGC2/Views/AdminChief/AddChief.cshtml
@model EntityLayer.Concrete.Chief
@{
    ViewBag.Title = "AddChief";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}

<h2>Şef Ekle</h2>
<a href="/AdminChief/Index/" class="closepopup"><i class="fas fa-minus-circle"></i></a>
@using (Html.BeginForm("AddChief", "AdminChief", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Adı")
        @Html.TextBoxFor(x => x.ChiefName, new { @class = "form-control" })
        @Html.Label("Soyadı")
        @Html.TextBoxFor(x => x.ChiefSurname, new { @class = "form-control" }) 
        @Html.Label("Rol")
        @Html.DropDownListFor(x => x.ChiefRole, new[] { new SelectListItem { Value = "A", Text = "Operasyon" }, new SelectListItem { Value = "B", Text = "Güvenlik" } }, "Seçim Yapınız", new { @class = "form-control" })
        @*@Html.Label("Şube No")
        @Html.TextBoxFor(x => x.BranchNo, new { @class = "form-control" })*@
        @Html.Label("Kullanıcı Adı")
        @Html.TextBoxFor(x => x.ChiefUsername, new { @class = "form-control" })
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.ChiefPassword, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary btn-lg btn-block">Oluştur</button>
     </div>
}

DGC2/Views/AdminChief/EditChief.cshtml
@model EntityLayer.Concrete.Chief
@{
    ViewBag.Title = "EditChief";
    Layout = "~/Views/Shared/_FormLayout.cshtml";
}

<h2>Şef Düzenleme</h2>
<a href="/AdminChief/Index/" class="closepopup"><i class="fas fa-minus-circle"></i></a>

@using (Html.BeginForm("EditChief", "AdminChief", FormMethod.Post))
{
<div class="form-group">
    @*@Html.Label("ID")*@
    @Html.HiddenFor(x => x.ChiefID, new { @class = "form-control" })
    @Html.Label("Adı")
    @Html.TextBoxFor(x => x.ChiefName, new { @class = "form-control" })
    @Html.Label("Soyadı")
    @Html.TextBoxFor(x => x.ChiefSurname, new { @class = "form-control" })
    @Html.Label("Şef Rolü")
    @Html.DropDownListFor(x => x.ChiefRole, new[] { new SelectListItem { Value = "A", Text = "Operasyon" }, new SelectListItem { Value = "B", Text = "Güvenlik" } }, "Seçim Yapınız", new { @class = "form-control" })
    @*@Html.Label("Şube No")*@
    @Html.HiddenFor(x => x.BranchNo, new { @class = "form-control" })
    @Html.Label("Kullanıcı Adı")
    @Html.TextBoxFor(x => x.ChiefUsername, new { @class = "form-control" })
    @Html.Label("Şifre")
    @Html.TextBoxFor(x => x.ChiefPassword, new { @class = "form-control" })
    @Html.Label("Giriş Tarihi")
    @Html.TextBoxFor(x => x.ChiefStartDate, new { @class = "form-control" })
    @Html.Label("Çıkış Tarihi")
    @Html.TextBoxFor(x => x.ChiefFinishDate, new { @class = "form-control" })
    @Html.Label("Statü")
    @Html.DropDownListFor(x => x.ChiefStatus, new[] { new SelectListItem { Value = "true", Text = "Aktif" }, new SelectListItem { Value = "false", Text = "Pasif" } }, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary btn-lg btn-block">Değişiklikleri Kaydet</button>
</div>
}

DGC2/Views/AdminChief/Index.cshtml
@using EntityLayer.Concrete
@model List<Chief>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<div class="card">
    <div class="card-header">
        <h3 class="card-title" style="font-size:30px; font-weight:700">Operasyon Şefi Düzenle</h3>
        <div class="card-tools">
            <a href="/AdminChief/AddChief/" class="btn btn-info float-right">Operasyon Şefi Girişi</a>
            
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
        <table id="example2" class="table table-bordered table-striped table-hover">
            <thead>

                <tr>
                    @*<th>ID</th>*@
                    <th>Adı</th>
                    <th>Soyadı</th>
                    @*<th>Şube Numarası</th>*@
                    <th>Şef Rolü</th>
                    <th>Giriş Tarihi</th>
                    <th>Çıkış Tarihi</th>
                    <th>Statü</th>
                    <th>Düzenle</th>
                    @*<th>Bilgiler</th>*@
                    @*<th>Sil</th>*@

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)

                {
                    <tr>
                        @*<td>@item.ChiefID</td>*@
                        <td>@item.ChiefName</td>
                        <td>@item.ChiefSurname</td>
                        @*<td>@item.BranchNo</td>*@
                        <td>
                        @if (item.ChiefRole == "A")
                        {
                            <p>Operasyon</p>
                        }
                        else
                        {
                            <p>Güvenlik</p>
                        }
                       </td>
                        <td>@item.ChiefStartDate</td>
                        <td>@item.ChiefFinishDate</td>
                        <td>@Html.Raw(item.ChiefStatus == true ? "<span class='badge badge-success'>Aktif</span>" : "<span class='badge badge-danger'>Pasif</span>")</td>
                        <td><a href="/AdminChief/EditChief/@item.ChiefID" class="btn btn-info">Düzenle</a></td>
                        @*<td><a href="#" class="btn btn-primary">Bilgiler</a></td>*@
                        @*<td><a href="/AdminChief/DeleteChief/@item.ChiefID" class="btn btn-danger">Sil</a></td>*@
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer clearfix">
       
     
    </div>

</div>